[tool.poetry]
name = "adventofcode2023"
version = "0.1.0"
description = ""
authors = ["Malte Fiala <z-c@ay.vc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "2.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
